---
driver:
  name: podman
platforms:
  - name: instance
    image: "fauust/docker-ansible:${MOLECULE_DISTRO:-debian-sid}"
    systemd: always
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      # - /tmp:/tmp
    command: "/lib/systemd/systemd"
    pre_build_image: true
provisioner:
  name: ansible
  # config_options:
  #   defaults:
  #     remote_tmp: /tmp/$USER
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
verifier:
  name: testinfra
