---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    # image: "fauust/docker-ansible:${MOLECULE_DISTRO:-debian-10}"
    image: "geerlingguy/docker-debian10-ansible:latest"
    command: /lib/systemd/systemd
provisioner:
  name: ansible
  env:
    ANSIBLE_GATHERING: explicit
    ANSIBLE_FORCE_COLOR: true
    ANSIBLE_PYTHON_INTERPRETER: /usr/bin/python3
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
verifier:
  name: testinfra
