---
driver:
  name: podman
platforms:
  - name: instance
    image: "fauust/docker-ansible:${MOLECULE_DISTRO:-debian-sid}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: "/lib/systemd/systemd"
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
  defaults:
    remote_tmp: /tmp/$USER
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
verifier:
  name: testinfra
