---
name: molecule

on:
  push:
  pull_request:
  schedule:
    - cron: "0 5 * * 2"

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - distro: ubuntu-20.04
            playbook: converge.yml

    steps:
      - name: start container
        run: |
          podman version
          podman run --name sys-test -ti --systemd=always fauust/docker-systemd:debian-10
